### PR TITLE
CORE-5177 Change from strict affinity type to scope string

### PR DESCRIPTION
**Pull request by gwinklosky**
A scope can be any string defined by the handle of a consumer's policy.  The public parameter was changed to allow any NSString rather than a strict type.

### CODE REVIEW

**Comment by tonyhuynh** [comment]
👍  makes sense to me

**Comment by ArtSabintsev** [comment]
👍

**Comment by ArtSabintsev** [comment]
If this is for external use, it'll need updates to the Podspec as well. A few other minor changes would be good, too. 

Do you need this for an external client?

**Comment by tonyhuynh** [comment]
@ArtSabintsev Not specifically. This is more for future proofing.

**Comment by ArtSabintsev** [comment]
ok cool.

**Pull request merged**
